# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  # name: .github
  description: ":atom: Repository used to organize everything around Organisations."
  topics: ivank, github, configuration, sync, org, organisation
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      contexts: []
    enforce_admins: false

# Labels: define labels for Issues and Pull Requests
# https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md
# https://github.com/DeFiCh/oss-governance-bot/blob/main/.github/labels.yml
labels:
- name: bug
  color: CC0000
  description: An issue with the system 🐛.
- name: good first issue
  color: 7057ff
- name: hackathon
  color: 85f920
- name: help wanted
  color: 008672
- name: question
  color: D876E3
- name: wontfix
  color: FFFFFF
- name: duplicate
  color: CFD3D7
- name: bug
  color: D73A4A
- name: documentation
  color: 0e8a16
  description: A PR that adds to documentation - used by Release Drafter
- name: hacktoberfest
  color: bdff3a
  description: 'Hacktoberfest. https://jenkins.io/blog/2018/10/01/hacktoberfest/'
- name: bugfix
  oldname: fix
  color: c9e85c
  description: A PR that fixes a bug - used by Release Drafter
- name: chore
  color: c9abea
  description: a PR that adds to maintenance - used by Release Drafter
- name: test
  color: d6e819
  description: A PR that adds to testing - used by Release Drafter
- name: pinned
  color: 5ed5e5
  description: 'Used to avoid stale[bot] marking a issue/PR stale'
- name: plugin-compatibility
  color: 8425c4
- name: stale
  color: ffffff
  description: 'Used by stale[bot] to mark a issue/PR stale'
- name: skip-changelog
  color: f44271
  description: A PR that is excluded from Release draft - used by Release Drafter
- name: removed
  color: aa0f1c
  description: A PR that removes code - used by Release Drafter
- name: deprecated
  color: e2b626
  description: A PR that deprecates code - used by Release Drafter
- name: breaking
  color: 640910
  description: A PR that is a breaking change - used by Release Drafter
- name: dev-tools
  color: 551a8b
  description: JCasC Community Bridge Dev-Tools Project
- name: dependencies
  color: 0366d6
  description: A PR that updates dependencies - used by Release Drafter
- name: release
  color: 640910
  description: A release
# Format and labels used aim to match those used by Ansible project
# https://github.com/marketplace/actions/github-labeler
- name: deprecated
  color: "fef2c0"
  description: "This issue/PR relates to a deprecated module."
- name: '🎈 Feature'
  color: "006b75"
  description: "This issue/PR relates to a feature request."
- name: major
  color: "c6476b"
  description: "Marks an important and likely breaking change."
- name: packaging
  color: "4071a5"
  description: "Packaging category"
- name: performance
  color: "555555"
  description: "Relates to product or testing performance."
- name: seo
  color: "2596be"
  description: "Relates to product or testing performance."
- name: skip-changelog
  color: "eeeeee"
  description: "Can be missed from the changelog."
- name: stale
  color: "eeeeee"
  description: "Not updated in long time, will be closed soon."
- name: test
  color: "0e8a16"
  description: "This PR relates to tests, QA, CI."
- name: gate
  color: "41b6e6"
  description: "Gate PR in Zuul CI"
## more info https://github.com/crazy-max/ghaction-github-labeler
- # automerge
  name: 'automerge'
  color: "8f4fbc"
  description: ""
- # approve
  name: "approved"
  color: "44d84c"
  description: ""
- # approve
  name: '✅ Approved'
  color: "44b5d8"
  description: ""
- # bot
  name: ":robot: bot"
  color: "69cde9"
  description: ""
- # bug
  name: ":bug: bug"
  color: "b60205"
  description: "This issue/PR relates to a bug."
- # dependencies
  name: ":game_die: dependencies"
  color: "0366d6"
  description: ""
- # documentation
  name: ":memo: documentation"
  color: "c5def5"
  description: "This issue/PR relates to or includes documentation."
- name: ":memo: docs"
  color: "4071a5"
  description: "This issue/PR relates to or includes documentation."
- # duplicate
  name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
- # enhancement
  name: ":sparkles: enhancement"
  color: "0054ca"
  description: "This issue/PR relates to a feature request."
- # feature request
  name: "✨ Fix"
  color: "0e8a16"
  description: ""
- # feedback
  name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- # future maybe
  name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- # good first issue
  name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
- # help wanted
  name: ":pray: help wanted"
  color: "4caf50"
  description: ""
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
- # investigate
  name: ":mag: investigate"
  color: "e6625b"
  description: ""
- # needs more info
  name: ":thinking: needs more info"
  color: "795548"
  description: ""
- # pinned
  name: ":pushpin: pinned"
  color: "28008e"
  description: ""
- # question
  name: ":question: question"
  color: "3f51b5"
  description: ""
- # sponsor
  name: ":sparkling_heart: sponsor"
  color: "fedbf0"
  description: ""
- # stale
  name: ":skull: stale"
  color: "237da0"
  description: ""
- # upstream
  name: ":eyes: upstream"
  color: "fbca04"
  description: ""
- # wontfix
  name: ":coffin: wontfix"
  color: "ffffff"
  description: ""

# commit sizes
- # size s
  name: ":smiley_cat: size S"
  color: "72cee3"
  description: ""
- # size M
  name: ":nauseated_face: size M"
  color: "e28743"
  description: ""

- # size L
  name: ":skull_and_crossbones: size L"
  color: "A82789"
  description: ""

- # size XL
  name: ":hourglass_flowing_sand: size XL"
  color: "5e03fc"
  description: ""

# Priority
- color: d93f0b
  name: priority/urgent-now
  description: Urgent fix, as fast as possible
- color: d93f0b
  name: priority/important-soon
  description: Will be important soon

# Triage
- color: b1f488
  name: triage/accepted
  description: Triage has been accepted

# Operating system
- color: 0d1d49
  name: os/win
- color: 0d1d49
  name: os/linux
- color: 0d1d49
  name: os/mac

# TODO
- name: 'todo :spiral_notepad:'
  color: 00B0D8

# Semantiv Versioning
- name: 'patch'
  color: 27A89F
  description: when you make backwards compatible bug fixes

- name: 'minor'
  color: 2729A8
  description: when you add functionality in a backwards compatible manner

- name: 'major'
  color: A827A3
  description: when you make incompatible API changes

# Actors
- name: 'github'
  color: 9ca49e
  description: software development and version control

# Do not merge stuff
- name: ':warning: do-not-merge'
  color: Bf811c
- name: ':warning: wip'
  color: A49ca3
- name: ':warning: wip'
  color: A49ca3
- name: 'wip'
  color: A49ca3
- name: 'work in progress'
  color: A49ca3

# Kinds
- name: 'kind/bug'
  color: 94213b
  description: Something isn't working
- name: 'kind/fix'
  color: 76b5c5
  description: Fix a bug
- name: 'kind/chore'
  color: 15791e
  description: Non feature change
- name: 'kind/feature'
  color: 15791e
  description: New feature
- name: 'kind/dependencies'
  color: 2673aa
  description: Pull requests that update a dependency file
- name: 'kind/docs'
  color: 26aa8a
  description: Non feature documentation change
- name: 'kind/question'
  color: 757915
  description: Generic question
- name: 'kind/refactor'
  color: 1e92bb
  escription: Non feature refactor change
- name: 'kind/stable'
  color: 1e92bb
  escription: Everything is working fine
- name: 'kind/github-action'
  color: 9adae7
  escription: Github action
- name: 'kind/github'
  color: 9adae7
  escription: Github setup
- name: 'kind/security'
  color: 32a6a8

# Needs
- name: 'needs/area'
  color: 8a3b94
- name: 'needs/triage'
  color: 3b7f94
- name: 'needs/kind'
  color: baaf4c

# Issues e.g., Area
- name: 'area/bug'
  color: 8a3b94
- name: 'area/github-action'
  color: 9adae7
- name: 'area/feature'
  color: 15791e
- name: 'area/chore'
  color: 15791e
- name: 'area/docs'
  color: 26aa8a
- name: 'area/question'
  color: 757915
- name: 'area/release'
  color: 879998
- name: 'area/dependencies'
  color: 8a3b94
- name: 'area/security'
  color: 32a6a8
