blank_issues_enabled: true
contact_links:
  - name: "👋 All other questions, including if you're not sure what to do."
    url: https://stackoverflow.com/
    about: The issue tracker is only meant for bug reports, feature requests and similar issues. Please ask your questions on the discussions forums and look for already existing answers.
  - name: "👣 Questions and Code Owner Help"
    about: "In case there is some serios matter you about to discuss with me"
    url: https://ivankatliarchuk.github.io/
