name: release-drafter

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      prerelease:
        description: Is this a pre-release
        required: true
        default: true
      publish:
        description: Publish release
        required: false
        default: false

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
